# What Python version is installed where:
# https://www.appveyor.com/docs/build-environment/#python

environment:
  matrix:
    - PYTHON: "C:\\Python38"
      TOX_ENV: "py38"

    - PYTHON: "C:\\Python39"
      TOX_ENV: "py39"

    - PYTHON: "C:\\Python310"
      TOX_ENV: "py310"

    - PYTHON: "C:\\Python311"
      TOX_ENV: "py311"

    - PYTHON: "C:\\Python312"
      TOX_ENV: "py312"

init:
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print( 8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install tox"
  - "%PYTHON%/Scripts/pip install wheel"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
